
// Auto generated by typewriter from c# code. Update coresponding c# code to re-generate this file.
import {HttpClientAPI} from '../components/httpClientProvider';

import {NotificationResponse} from '../model/notificationResponse';


export function get_getNotification_URL(clearNew: boolean, currentItemCount: number) {
  return `/api/notification/GetNotification{clearNew, currentItemCount}?clearNew=${clearNew}&currentItemCount=${currentItemCount}`;
}export function get_readNotification_URL(id: number) {
  return `/api/notification/ReadNotification${id}`;
}
export function getNotification(api: HttpClientAPI,clearNew: boolean, currentItemCount: number) {
  return api.http<NotificationResponse[]>(`/api/notification/GetNotification{clearNew, currentItemCount}?clearNew=${clearNew}&currentItemCount=${currentItemCount}`, { method: 'get'  });
}

export const getNotificationCount_URL = '/api/notification/GetNotificationCount';
export function getNotificationCount(api: HttpClientAPI) {
  return api.http<number>('/api/notification/GetNotificationCount', { method: 'get'  });
}export function readNotification(api: HttpClientAPI,id: number) {
  return api.http<void>(`/api/notification/ReadNotification${id}`, { method: 'get'  });
}
