
// Auto generated by typewriter from c# code. Update coresponding c# code to re-generate this file.
import {HttpClientAPI} from '../components/httpClientProvider';





export const getAllStickers_URL = '/api/stickers/getAllStickers';
export function getAllStickers(api: HttpClientAPI) {
  return api.http<{ [key: string]: string[]; }>('/api/stickers/getAllStickers', { method: 'get'  });
}